# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import users_pb2 as users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get = channel.unary_unary(
        '/users.Users/get',
        request_serializer=users__pb2.UsersRequest.SerializeToString,
        response_deserializer=users__pb2.UsersReply.FromString,
        )
    self.get_stream = channel.unary_stream(
        '/users.Users/get_stream',
        request_serializer=users__pb2.UsersRequest.SerializeToString,
        response_deserializer=users__pb2.UsersReply.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=users__pb2.UsersRequest.FromString,
          response_serializer=users__pb2.UsersReply.SerializeToString,
      ),
      'get_stream': grpc.unary_stream_rpc_method_handler(
          servicer.get_stream,
          request_deserializer=users__pb2.UsersRequest.FromString,
          response_serializer=users__pb2.UsersReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'users.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
